String emailStr="Email";
String emailValidationStr="Please enter ypur email";
String passwordStr="Enter your password";
String passwordValidationStr="Please enter your password";
String userStr="Enter your username";
String userNameValidation="Please enter your username";
String nameStr="Enter your name";
String addressStr="Enter your address";
String phoneStr="Enter your phone number";
