// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW3lGPXalkI09bba21T2CiasxddbENCUQ',
    appId: '1:1028812058845:web:4ab196f6a2967620d2ab34',
    messagingSenderId: '1028812058845',
    projectId: 'learning-362c2',
    authDomain: 'learning-362c2.firebaseapp.com',
    storageBucket: 'learning-362c2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQBgWC4xiOFZVF8AwQo43MxS40m8sgINA',
    appId: '1:1028812058845:android:d759a4fe3aa0691bd2ab34',
    messagingSenderId: '1028812058845',
    projectId: 'learning-362c2',
    storageBucket: 'learning-362c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyTPD3wYkt61tSn_3K3bYUoxMXKMjQePo',
    appId: '1:1028812058845:ios:e1782f86b614559dd2ab34',
    messagingSenderId: '1028812058845',
    projectId: 'learning-362c2',
    storageBucket: 'learning-362c2.firebasestorage.app',
    iosBundleId: 'com.aayusha.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyTPD3wYkt61tSn_3K3bYUoxMXKMjQePo',
    appId: '1:1028812058845:ios:8d2ad5df75a4fd45d2ab34',
    messagingSenderId: '1028812058845',
    projectId: 'learning-362c2',
    storageBucket: 'learning-362c2.firebasestorage.app',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW3lGPXalkI09bba21T2CiasxddbENCUQ',
    appId: '1:1028812058845:web:e8788bee45fd8be9d2ab34',
    messagingSenderId: '1028812058845',
    projectId: 'learning-362c2',
    authDomain: 'learning-362c2.firebaseapp.com',
    storageBucket: 'learning-362c2.firebasestorage.app',
  );
}
